language: go
env: BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
matrix:
  include:
  - go: 1.11.x
    env: GO111MODULE=on
    script:
    - make vet
    - make test
  - go: 1.12.x
    script:
    - make vet
    - make test
    - OS=darwin make build
    - OS=windows make build
    - OS=linux make build
