language: go
env: BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
matrix:
  include:
    - go: 1.10.x
      script:
        - make vet
        - make test
    - go: 1.11.x
      env: GO111MODULE=on
      script:
        - make vet
        - make test
    - go: 1.11.x
      env:
        - GO111MODULE=off
      script:
        - make
        - OS=darwin make
        - OS=windows make
deploy:
  provider: releases
  api_key:
    secure: OURdioXqvsXxe5PgQATXZAqlga5EuseT9TDs4h8Tj32Hczf791nIHn5Y7kDWW9vU2pqDidb5YNStKrKF+LfBHijl69KNEh1CDXH07sbYjbWIlbfeU2sJOPPcoK9NtduPYBG/lN22u3b/cgCZZqEAOPBnsh6dJVS8vjcD0xtySShVsYETqyRbjhSxwzJ7835uObzQ+DwNrF6BPMgqC82pgumkR+ybLTIwh3+RYpEnCjbGFh8RiOBCKKLYn26m7Gn26eOOHKLlSZCYOrld4ICnmRiqxz0rZTUYC8mpOuO1UK0vd82DbFkVGCBfOBgxh1QlpSJmyDLOZPp41mKo47vhf0bMR/0Jt4JHqJwnOwKKhPuZXnddqS0SqzbdLIInZtoGJ3RhRktWiP5nzzC/PJf6EAkMNPputgCB8q9Thvyh2UrZ9GBrYslcwIHPa1L9fXxmPTYvl7KDJ+YyCI36qSgR4XKHTTvhdePBHyJI31ZHjk/793LvufuvezpBHBpmY17VOH8LWKPpx/ShtHimpkSBzTd6TRaYhSQ7p4OPFNOKuNWV8o6yvIzpLts1NYiKhkcXieyowryeC3vSMd3+6cBPF/0DcAj2wrXH4q6pEesOr07mZDE0kufIurcF08Gsj6lhDy9rmHTkaVeba0vaa7G8lCqzdp9FkF44H2EFoAw/5iI=
  file: build/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: gini/dexter
    tags: true
branches:
  except:
    - "/^[0-9]/"
